### ISSUE TITLE
Redmine 0.8.4

### ISSUE THREAD

**Issue by dsovino** [MischaTheEvil/redmine_google_calendar#2]
Hi, I'm getting the following error log while installing Google Calendar on 0.8.4

NameError (uninitialized constant TZInfo::Country):
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:276:in `load_missing_constant'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:468:in`const_missing'
    /vendor/plugins/redmine_google_calendar/app/controllers/google_calendar_controller.rb:37:in `tzinfo_from_offset'
    /vendor/plugins/redmine_google_calendar/app/controllers/google_calendar_controller.rb:13:in`show'
    /vendor/rails/actionpack/lib/action_controller/base.rb:1166:in `send'
    /vendor/rails/actionpack/lib/action_controller/base.rb:1166:in`perform_action_without_filters'
    /vendor/rails/actionpack/lib/action_controller/filters.rb:579:in `call_filters'
    /vendor/rails/actionpack/lib/action_controller/filters.rb:572:in`perform_action_without_benchmark'
    /vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    C:/WINDOWS/ruby/lib/ruby/1.8/benchmark.rb:293:in`measure'
    /vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    /vendor/rails/actionpack/lib/action_controller/rescue.rb:201:in`perform_action_without_caching'
    /vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:13:in `perform_action'
    /vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:33:in`cache'
    /vendor/rails/activerecord/lib/active_record/query_cache.rb:8:in `cache'
    /vendor/rails/actionpack/lib/action_controller/caching/sql_cache.rb:12:in`perform_action'
    /vendor/rails/actionpack/lib/action_controller/base.rb:529:in `send'
    /vendor/rails/actionpack/lib/action_controller/base.rb:529:in`process_without_filters'
    /vendor/rails/actionpack/lib/action_controller/filters.rb:568:in `process_without_session_management_support'
    /vendor/rails/actionpack/lib/action_controller/session_management.rb:130:in`process'
    /vendor/rails/actionpack/lib/action_controller/base.rb:389:in `process'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:149:in`handle_request'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:107:in `dispatch'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in`synchronize'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:104:in `dispatch'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:120:in`dispatch_cgi'
    /vendor/rails/actionpack/lib/action_controller/dispatcher.rb:35:in `dispatch'
    /vendor/rails/railties/lib/webrick_server.rb:112:in`handle_dispatch'
    /vendor/rails/railties/lib/webrick_server.rb:78:in `service'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:162:in `start'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:95:in `start'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:92:in`each'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:92:in `start'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:23:in`start'
    C:/WINDOWS/ruby/lib/ruby/1.8/webrick/server.rb:82:in `start'
    /vendor/rails/railties/lib/webrick_server.rb:62:in`dispatch'
    /vendor/rails/railties/lib/commands/servers/webrick.rb:66
    C:/WINDOWS/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:27:in `gem_original_require'
    C:/WINDOWS/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:27:in`require'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:355:in`new_constants_in'
    /vendor/rails/activesupport/lib/active_support/dependencies.rb:510:in `require'
    /vendor/rails/railties/lib/commands/server.rb:39
    C:/WINDOWS/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:27:in`gem_original_require'
    C:/WINDOWS/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:27:in `require'
    /script/server:3

I'm looking forward for your reply.

Thanx in advance.

Daniel

**Comment by MischaTheEvil** [comment]
Hello Daniel,

Sorry for the late reply but didn't got notified about this issue someway...
Regarding the error you are experiencing: it seems most likely that you don't have the `tzinfo` gem installed. See http://www.redmine.org/wiki/redmine/PluginGoogleCalendar#Prerequisites.

Please let me know if this solves the issue...

Kind regards,

Mischa.

**Comment by MischaTheEvil** [comment]
Got a reply from Daniel confirming that my hint indeed solved his issue.
