### ISSUE TITLE
Overview window

### ISSUE THREAD

**Issue by ghost** [MischaTheEvil/redmine_google_calendar#5]
Hi, thanks for the great plugin. 

I am wondering if there is a way to remove this bullet point from the overview window:

"
Google Calendar IFrame: <iframe src="http://www.google.com/calendar/embed?src=[...]" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
"

**Comment by MischaTheEvil** [comment]
This is covered in the FAQ at http://www.redmine.org/wiki/redmine/PluginGoogleCalendar#FAQ.
