### ISSUE TITLE
Calendar tab visible only with admin account

### ISSUE THREAD

**Issue by darkpotpot** [MischaTheEvil/redmine_google_calendar#7]
Hello, I tried this plugin but I have a little problem.

I followed the documentation in order to add a google calendar tab in a project. At first, I thought everything was ok because I could see the tab. But the problem is that users can't see it. So I tried to login with a user account and, indeed, I can't see the tab.

Is there anything to do in order to make it viewable for every user ?

Thanks in advance,

**Comment by lhaemmerle** [comment]
I just experienced the same problem. It seems that the Google calendar tab is only visible for users with administration privileges. Tested with  Redmine 0.9.4.stable and  the Google Calendar Plugin 0.3.0-dev.

Any idea how to solve this?

**Comment by darkpotpot** [comment]
Yeah, I found the solution.
You have to login with your admin account, go to "administration/roles and permissions". For each role you want to be able to see the calendar, you have to select it and then check the "View google calendar tab" checkbox.

Hope it will help you.

**Comment by lhaemmerle** [comment]
Thank you very much. This solved the problem :-)
